version: 2.1
orbs:
  node: circleci/node@1.1.6

jobs:
  build:
    steps:
      - checkout
      - run: sudo apt-get install postgresql
      - run: sudo apt-get install -y git-crypt
      - run: echo "$GIT_CRYPT_KEY" > key.key
      - run: base64 -di key.key > git-crypt.key
      - run: git-crypt unlock git-crypt.key
  client:
    executor:
      name: node/default
    steps:
      - checkout
      - run: cd frontend && npm install
  server:
    executor:
      name: node/default
    steps:
      - checkout
      - run: cd backend && npm install && npm test
workflows:
  client:
    jobs:
      - build
      - client
  server:
    jobs:
      - build
      - server
