version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-client:
    executor:
      name: node/default
    steps:
      - checkout
      - run: sudo apt-get install -y git-crypt
      - run: echo "$GIT_CRYPT_KEY" | base64 -d > git-crypt.key
      - run: git-crypt unlock git-crypt.key
      - run: cd frontend && npm install
  build-and-test-server:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd backend && npm install && npm test
workflows:
  client:
    jobs:
      - build-client
  server:
    jobs:
      - build-and-test-server
